# Generated by Django 2.1.7 on 2019-02-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
