# Generated by Django 2.1.7 on 2019-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190214_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
