# Generated by Django 2.1.7 on 2019-02-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
