# Generated by Django 2.1.7 on 2019-02-14 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_auto_20190214_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
